services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  
      POSTGRES_DB: cinema
      # thisis a hasura db that u want to connect with
    volumes:
      - hasura_postgres_data:/var/lib/postgresql/data
  hasura:
    image: hasura/graphql-engine:v2.42.0
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/cinema  
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}  
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_JWT_SECRET}  
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"  
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous  
    volumes:
      - hasura_metadata:/hasura-metadata

volumes:
  hasura_postgres_data:
  hasura_metadata:
