services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: cinema
      # thisis a hasura db that u want to connect with
    volumes:
      - hasura_postgres_data:/var/lib/postgresql/data
  hasura:
    image: hasura/graphql-engine:v2.42.0
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgresuser:postgrespassword@postgres:5432/cinema
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "this_is_a_super_secret_key_1234567890"}'
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous # this is used to allow a user not to be asked a JWT when a user is tried to sign up ok am of God .......
    volumes:
      - hasura_metadata:/hasura-metadata

volumes:
  hasura_postgres_data:
  hasura_metadata:
